include:
  - project: qtud/ci-template
    ref: master
    file: template-ci-vnpay.yaml

variables:
  IMAGE_NAME: n8n
  LOCAL_REGISTRY: registry.vnpay.vn
  NAMESPACE: n8ntt
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  TAG_RUNNER: BLC
  DOCKERFILE_NAME: Dockerfile
  CI_PROJECT_DIR: .
  PROJECT_NAME: n8ntt

stages:
  - scan
  - dockerize
  - publish
