/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";
import { AddedFact } from "../../../../types/AddedFact";
export declare const AddFactsRequest: core.serialization.Schema<serializers.AddFactsRequest.Raw, Zep.AddFactsRequest>;
export declare namespace AddFactsRequest {
    interface Raw {
        facts?: AddedFact.Raw[] | null;
    }
}
