/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";
import { FactRatingInstruction } from "../../../../types/FactRatingInstruction";
export declare const CreateSessionRequest: core.serialization.Schema<serializers.CreateSessionRequest.Raw, Zep.CreateSessionRequest>;
export declare namespace CreateSessionRequest {
    interface Raw {
        fact_rating_instruction?: FactRatingInstruction.Raw | null;
        metadata?: Record<string, unknown> | null;
        session_id: string;
        user_id?: string | null;
    }
}
