/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";
import { FactRatingInstruction } from "../../../../types/FactRatingInstruction";
export declare const UpdateSessionRequest: core.serialization.Schema<serializers.UpdateSessionRequest.Raw, Zep.UpdateSessionRequest>;
export declare namespace UpdateSessionRequest {
    interface Raw {
        fact_rating_instruction?: FactRatingInstruction.Raw | null;
        metadata: Record<string, unknown>;
    }
}
